[package]
name = "rustyboy-pc"
version = "0.1.0"
authors = ["felixleveille <flxleveille@gmail.com>"]
edition = "2018"

[dependencies]
glium = "*"
console = "0.7.5"
rustyboy-core = { path = "../core" }
clap = { version = "4.5.20", features = ["derive"] }
rand = "0.8.5"
